### ISSUE TITLE
Can't boot when a CF card is installed on XTCF

### ISSUE THREAD

**Issue by A-Small-Mice** [spark2k06/Micro-XTCF#2]
![20230208_133055](https://user-images.githubusercontent.com/112596327/217434238-39018c87-29cd-4634-acf2-bf4f887051d2.jpg)
![20230208_133102](https://user-images.githubusercontent.com/112596327/217434248-a7819550-4f8c-4a88-9fc6-9905c135d1fe.jpg)

I made my XTCF from the data given. It does actually work, unless a CF card is installed. I can see that the XTIDE BIOS is loaded normally when the CF card is not installed. However, if I install a CF card, the system BIOS does not work and the computer freezes. The LED is always lit.

I tried using the XTCF for IBM 5150 and XT clones, but the results were the same. I also tried various types of CF cards.

I don't know how to solve it. Can you help me?

**Comment by spark2k06** [comment]
You need mirror type CF connectors, the ones that are placed on the opposite side to the rest of the components.

They are not easy to get, which is part of the reason why I have stopped selling them in favor of the new model I have called XTSD.

**Comment by A-Small-Mice** [comment]
What is the mirror type CF connector? I compared my CF connectors with yours from the picture, but I can't find any difference.

**Comment by A-Small-Mice** [comment]
![20230208_175533](https://user-images.githubusercontent.com/112596327/217484890-dfa93a2a-722c-479c-b4d9-86306456e26b.jpg)
![20230208_175539](https://user-images.githubusercontent.com/112596327/217484902-8a61422f-8ea4-4e1f-bdde-a978e077e4af.jpg)
![20230208_175618](https://user-images.githubusercontent.com/112596327/217484915-229cc732-5992-4f26-8bc8-76933cfe58f1.jpg)

I reversed the CF card and installed it. XT-IDE BIOS is loaded, the CF card is also found by the BIOS. But there is an error.


------

![O1CN019nNtCn2AI2DJUOjEd_!!840898179](https://user-images.githubusercontent.com/112596327/217486120-768e6bce-c22e-4f9e-b5a7-9d8f01b44c48.png)
I wonder if this is the mirror type CF connector(板下) you mentioned.

**Comment by spark2k06** [comment]
Exactly, the card has to look like this, with the mirror type connector, because the insertion rails are correct:

![image](https://user-images.githubusercontent.com/3509674/217488113-f3014c98-13b6-47d3-af7e-06398a2b1fba.png)

**Comment by spark2k06** [comment]
Anyway, in the XTIDE universal bios, make sure you choose XTCF instead of XTIDE rev1 or rev2:

![image](https://user-images.githubusercontent.com/3509674/217490641-0a79b9d9-c6cb-4eea-b4b9-36d1049a954c.png)

**Comment by A-Small-Mice** [comment]
![20230208_184722](https://user-images.githubusercontent.com/112596327/217494926-f753ecc6-b76a-41f7-976f-7cfa030bddca.jpg)
![20230208_184744](https://user-images.githubusercontent.com/112596327/217494951-e7245c53-641b-4a40-9478-53180a9b3b42.jpg)

Yeah! Finally! My XT-CF does work!

You corrected my two mistakes.

* **Mistake 1** I have no mirror type CF card connector, so the CF card was installed in the wrong direction. It caused system to freeze.
* **Mistake 2** I used XTIDE rev 1 as controller instead of XT-CF.

**Comment by spark2k06** [comment]
Great! I'm glad it's working for you, I close the case.
