### ISSUE TITLE
ROM window size

### ISSUE THREAD

**Issue by Leo-PL** [spark2k06/Micro-XTCF#3]
I see no discussions enabled, so I'm asking here:
Is the option ROM window size fixed at 8kB? I only see the window start address as variable.
I'm wondering if it could be extended by altering the SPLD image, as the ROM socket in theory can accept up to 64kB chips.

Which, makes it tempting to cram multiple option ROMs beside XTIDE universal BIOS - to avoid modding an XT board with  ROM size fixed at 8kB - into a single, bigger chip.

Thanks in advance for the reply.

**Comment by Leo-PL** [comment]
After looking at the design, I'll reply to myself: HW design will need an alteration, some 28C64 pins have different functions than 27C128/256/512, and here only !ROMW could double as A14. A15 (here RDY/!BUSY) and A13 (N/C) would have to be bodge-wired in hardware.

**Comment by spark2k06** [comment]
Sorry, but this PCB is not designed for more than 8Kb ROM size.
